#name: Node.js Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-queue@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint
      - run: |
          echo ${{ github.event.head_commit.committer.username }}
          echo ${{ github.event.head_commit.author.username }}
          exit 1
      - name: 'Automated Version Bump'
        if: ${{ github.event.head_commit.committer.username == 'dependabot[bot]' }}
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
          version-type: 'patch'
      - name: 'Automated Version Bump'
        if: ${{ github.event.head_commit.committer.username != 'dependabot[bot]' }}
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
