#name: Node.js Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-queue@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          patch-wording:  'patch,fixes,Bump'
          tag-prefix: 'v'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
